fix(subheader): add tooltip on test icon when testing unpublished bot
takenet/blip-components pull request #150
Opened 2021-11-04 14:14 UTC by rafael-santiago-take

fix(subheader): add tooltip on test icon when testing unpublished bot

2021-11-04 14:24 UTC, EricJangola approved these changes

2021-11-04 19:37 UTC, jujucasseb approved these changes

2021-11-05 18:10 UTC, mhnakashima commented on src/components/subheaderIcons/SubheaderIconsView.scss
> +            left: 1.8rem !important;
If you do something like this the result is going to be the same and it's not using !important (we must avoid it).

.action-icons {
    display: inline-flex;

    li {
        .toolTipUnpublishedFlow {
            tooltip {
                tip {
                    left: 1.8rem;
                }
            }
        }
    }
}

2021-11-05 18:14 UTC, mhnakashima requested changes
.action-icons {
    display: inline-flex;
    li {
        .toolTipUnpublishedFlow {
            tooltip {
                tip {
                    left: 1.8rem;
                }
            }
        }
    }
}

We should avoid !important because can generate unexpected behaviours..
When we use solutions like nest, the css scope is protected and other classes will not be affected if another place has class with name .toolTipUnpublishedFlow

2021-11-05 20:37 UTC, rafael-santiago-take commented on src/components/subheaderIcons/SubheaderIconsView.scss
> +            left: 1.8rem !important;
ok

2021-11-08 11:31 UTC, mhnakashima approved these changes

2021-11-08 11:59 UTC, merged